 <html>
	<head>
		
	</head>
	<body>
			{foreach from = $articles item = article}
				<h3>{$article.titre}</h3>
					<p>{$article.texte}</p>
                    <img src="img/vign/{$article.id}.jpg">
					 ecrit le : {$article.date}
					
				{if ( $connecte )}
					<br><br>
					<a href="article.php?id={$article.id}" class="btn btn-primary">Modifier</a>
					<a href="supprimer-article.php?id={$article.id}" class="btn btn-danger"> Supprimer</a>  
				 
				{/if}
				
				<hr>
			{/foreach}
			
			<div class="pagination">
				<ul>
					<li class="prev{if $page<=1} disabled{/if}">
						<a href="{if $page<=1}#null{else}?p={$page-1}{/if}&r={$rech}">&larr;Precedent</a>
					</li> <!-- reprensente des "left-arrow" -->
									
					{for $i=1 to $nb_pages}<!-- On boucle jusqu a l'avant dernier page-->
						<li{if $page==$i } class="active"{/if}>
							<a href="?p={$i}&r={$rech}">{$i}</a>
						</li>						
					{/for}<!-- On arrete de boucler --> 
					{$rech_encode}
					<li class="next{if $page>=$nb_pages} disabled{/if}">
						<a href="{if $page>=$nb_pages}#null{else}?p={$page+1}{/if}&r={$rech}">Suivant&rarr;</a>
					</li>
				</ul>
			</div>			
	</body>
</html>
